name: nyayanow
description: NyayaNow - Legal Awareness & AI Guide (Flutter Starter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  http: ^1.2.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  yaml: ^3.1.2


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: NotoSansKannada
      fonts:
        - asset: assets/fonts/NotoSansKannada-VariableFont_wght.ttf
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-VariableFont_wdth_wght.ttf




