name: nyayanow
description: NyayaNow LegalTech â€” National Justice Platform (Enterprise Flutter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5
  http: ^1.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  # Optional future UX
  speech_to_text: ^7.0.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

  fonts:
    - family: NotoSansKannada
      fonts:
        - asset: assets/fonts/NotoSansKannada-VariableFont_wght.ttf
    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-VariableFont_wdth_wght.ttf
